[package]
name = "li-nvidia"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
open = "5.3.1"
 reqwest= {version="*",features = ["json","blocking"]}
scraper = "0.22.0"
serde_json = "1.0.134"
tokio = {version = "*",features = ["full"]}

[dev-dependencies]